# Generated by Django 4.2.2 on 2023-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstinctLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_method", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "path",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("request", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status_code",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("request_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
