# Generated by Django 4.2.2 on 2023-07-22 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("internal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="instinctlog",
            table="instinct_log",
        ),
    ]
