# Generated by Django 4.2.2 on 2023-07-22 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("internal", "0002_alter_instinctlog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="instinctlog",
            table="internal_instinct_log",
        ),
    ]
